[package]
authors = ["Evan Vigil-McClanahan <mcclanahan@gmail.com>"]
edition = "2018"
name = "todo"
version = "0.1.0"

[dependencies]
chrono = "0.4.11"
clap = "2.33.0"
filetime = "0.2.8"
toml = "0.5.6"
